import psycopg2
from datetime import datetime
from bdd.env import *
import requests

conn = psycopg2.connect(database=PG_DB,
                        user=PG_USER,
                        host=PG_HOST,
                        password=PG_PASSWORD,
                        port=PG_PORT)
cur = conn.cursor()

def init_db(cur):
    # crée les tables si elles n'existent pas
    cur.execute("CREATE TABLE IF NOT EXISTS users (id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, username varchar, password_hash varchar);")
    cur.execute("CREATE TABLE IF NOT EXISTS push_notification (id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id int, url varchar, sensor_check_id int);")
    cur.execute("CREATE TABLE IF NOT EXISTS sensor_check (id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, type varchar, relation varchar, value float);")
    cur.execute("CREATE TABLE IF NOT EXISTS sensor (time int, temperature float, humidity float, co2 float);")
    cur.execute("CREATE TABLE IF NOT EXISTS donnees_meteo (time int, temperature float, humidity float);")
    conn.commit()

def insert_sensor_value(humidity=None, temperature=None, co2=None):
    time_stamp = int(datetime.now().timestamp())
    str_columns = ""
    str_values = ""
    if humidity is not None:
        str_columns = ", humidity"
        str_values = ", " + str(humidity)
    if temperature is not None:
        str_columns += ", temperature"
        str_values += ", " + str(temperature)
    if co2 is not None:
        str_columns += ", co2"
        str_values += ", " + str(co2)

    str_columns = str_columns[1:]
    str_values = str_values[1:]

    cur.execute(f"INSERT INTO sensor (time, {str_columns}) VALUES ({time_stamp}, {str_values});")
    conn.commit()


def insert_meteo_value(humidity=None, temperature=None):
    time_stamp = int(datetime.now().timestamp())
    str_columns = ""
    str_values = ""
    if humidity is not None:
        str_columns = ", humidity"
        str_values = ", " + str(humidity)
    if temperature is not None:
        str_columns += ", temperature"
        str_values += ", " + str(temperature)

    str_columns = str_columns[1:]
    str_values = str_values[1:]

    cur.execute(f"INSERT INTO donnees_meteo (time, {str_columns}) VALUES ({time_stamp}, {str_values});")
    conn.commit()

def get_old_data(time1, time2):
    cur.execute(f"SELECT * FROM sensor WHERE time > {time1} AND time < {time2};")
    return cur.fetchall()

def get_old_data_meteo(time1, time2):
    cur.execute(f"SELECT * FROM donnees_meteo WHERE time > {time1} AND time < {time2};")
    return cur.fetchall()

def envoyer_notification(message, url):
    requests.post(str(url), data = str(message).encode(encoding='utf-8'))

def verif_notifs(type, valeur):
    bdd.main.cur.execute(f"select * FROM sensor_check WHERE type='{type}'")
    for tuple_check in bdd.main.cur.fetchall():
        if tuple_check[2] == ">":
            if valeur > tuple_check[3]:
                bdd.main.cur.execute(f"select * FROM push_notification WHERE sensor_check_id={tuple_check[0]}")
                liste_url = bdd.main.cur.fetchall()
                for tuple_url in liste_url:
                    envoyer_notification(f"{type} : {valeur}", tuple_url[2])
        elif tuple_check[2] == "<":
            if valeur < tuple_check[3]:
                bdd.main.cur.execute(f"select * FROM push_notification WHERE sensor_check_id={tuple_check[0]}")
                liste_url = bdd.main.cur.fetchall()
                for tuple_url in liste_url:
                    envoyer_notification(f"{type} : {valeur}", tuple_url[2])