/*--- ---------------------------------------
--- Partie 1
--- ---------------------------------------
*/
-- suppression des tables
DROP TABLE IF EXISTS LIG_CMD;
DROP TABLE IF EXISTS ARTICLE;
DROP TABLE IF EXISTS COMMANDE;
DROP TABLE IF EXISTS FOURNISSEUR;
DROP TABLE IF EXISTS MAGASIN;
DROP TABLE IF EXISTS CLIENT;


CREATE TABLE FOURNISSEUR(
FRS_NUM CHAR(8) NOT NULL,
FRS_NOM CHAR(25),
PRIMARY KEY (FRS_NUM)
);

CREATE TABLE MAGASIN
(
MAG_NUM CHAR(8) NOT NULL,
MAG_LOC CHAR(25) NOT NULL,
PRIMARY KEY (MAG_NUM)
);

CREATE TABLE CLIENT
(
CLT_NUM CHAR(8) NOT NULL,
CLT_NOM CHAR(25) NOT NULL,
CLT_PRENOM CHAR(20) NOT NULL,
CLT_LOC CHAR(25),
PRIMARY KEY (CLT_NUM)
);

CREATE TABLE ARTICLE
(
ART_NUM CHAR(8) NOT NULL,
ART_FRS CHAR(8) NOT NULL,
ART_NOM CHAR(25),
ART_PV FLOAT(4),
ART_PA FLOAT(4),
ART_COUL CHAR(10),
ART_POIDS FLOAT(4),
PRIMARY KEY (ART_NUM),
CONSTRAINT FK_ARTICLE_FK_ARTICL_FOURNISS
FOREIGN KEY (ART_FRS) REFERENCES FOURNISSEUR (FRS_NUM)
);

CREATE TABLE COMMANDE
(
CMD_NUM CHAR(8) NOT NULL,
CMD_CLT CHAR(8) NOT NULL,
CMD_MAG CHAR(8) NOT NULL,
CMD_DATE DATE NOT NULL,
PRIMARY KEY (CMD_NUM),
CONSTRAINT FK_COMMANDE_FK_COMMAN_CLIENT
FOREIGN KEY (CMD_CLT) REFERENCES CLIENT (CLT_NUM),
CONSTRAINT FK_COMMANDE_FK_COMMAN_MAGASIN
FOREIGN KEY (CMD_MAG) REFERENCES MAGASIN (MAG_NUM)
);

CREATE TABLE LIG_CMD
(
LCD_ART CHAR(8) NOT NULL,
LCD_CMD CHAR(8) NOT NULL,
LCD_QTE INT(4),
LCD_PU INT(4),
PRIMARY KEY (LCD_ART, LCD_CMD),
CONSTRAINT FK_LIG_CMD_FK_CONCER_ARTICLE
FOREIGN KEY (LCD_ART) REFERENCES ARTICLE (ART_NUM),
CONSTRAINT FK_LIG_CMD_FK_LIG_CM_COMMANDE
FOREIGN KEY (LCD_CMD) REFERENCES COMMANDE (CMD_NUM)
);

